spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wfx?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8

mybatis:
  type-aliases-package: com.qf.wfx.merchant.beans
  mapper-locations: classpath:mappers/*Mapper.xml

